name: Dockerfile_validation

on:
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: code_checkout
      uses: actions/checkout@v2
    - name: Check_syn
      run: docker build --progress=plain --no-cache -f Dockerfile.test1 .
      with:
        context: .
        file: ./Dockerfile.test1
      
    
