name: Validation
on:
  pull_request:
    branches:
    - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Validate Dockerfile
      uses: redcoolbeans/dockerlint-action@v3
      with:
        file: ./Dockerfile.test1
