name: Dockerfile_validation

on:
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: code_checkout
      uses: actions/checkout@v2

    - name: Check_syn
      run: ./ --progress=plain --no-cache -f Dockerfile.test1 .
